Hausklimatisierung: I2C_Master.h File Reference
I2C_Master.h File Reference
#include <Arduino.h>
#include <Wire.h>
Functions
void I2C_Master_Setup (long nFrequency)
I²C master setup.
void I2C_Master_Steady ()
I²C master steady call.
int I2C_SendRequest (int nSlaveNo, const char *const pszRequest)
Send request to slave.
int I2C_GetResponse (int *pnSlaveNo, char *pszResponse, unsigned long *pnResponseTime=nullptr)
Get text response for last request.
bool I2C_IsReady ()
See if ready for a request.
bool I2C_HasReply ()
See if request has been fulfilled.
Variables
const int I2C_DATA_MAX = 132
max request and response length
Function Documentation
I2C_GetResponse()
int I2C_GetResponse (int * pnSlaveNo, char * pszResponse, unsigned long * pnResponseTime = nullptr)
Get text response for last request.
Gets a received text response.
Parameters
pnSlaveNo slave number the request was targeted
pszResponse storage for received response
pnResponseTime duration between request transmit start and response delivery in microseconds
Returns
>=0 length on success, -1 if busy, -3 if timed out, -4 while no outstanding response
Definition at line 108 of file I2C_Master.cpp.
 {
   switch ( nI2CState )
   {
   case I2C_BUSY:
     return -1;                                  // fail if busy
   case I2C_READY:
     return -4;                                  // fail if no outstanding response
   case I2C_TIMEOUT:
     *pszResponse = 0;
     *pnSlaveNo = nSlaveNoLast;
     if ( pnResponseTime != nullptr )
       *pnResponseTime = nResponseTimeOut;
     nI2CState = I2C_READY;
     return -3;                                  // fail if timed out
   case I2C_DONE:
     strcpy(pszResponse, szResponse);            // return received answer
     *pnSlaveNo = nSlaveNoLast;
     if ( pnResponseTime != nullptr )
       *pnResponseTime = nResponseTime;
     nI2CState = I2C_READY;
     return nResponseLength;
   }
   return -1;                                    // should not happen, fail
 }
References I2C_BUSY, I2C_DONE, I2C_READY, I2C_TIMEOUT, nI2CState, nResponseLength, nResponseTime, nResponseTimeOut, nSlaveNoLast, and szResponse.
Referenced by Task_100ms().
I2C_HasReply()
bool I2C_HasReply ()
See if request has been fulfilled.
See if request has been fulfilled.
Returns
true if I2C previous command got a reply
Definition at line 141 of file I2C_Master.cpp.
 {
   return ( nI2CState == I2C_DONE ) || ( nI2CState == I2C_TIMEOUT );
 }
References I2C_DONE, I2C_TIMEOUT, and nI2CState.
I2C_IsReady()
bool I2C_IsReady ()
See if ready for a request.
See if ready for a request.
Returns
true if I2C is ready
Definition at line 135 of file I2C_Master.cpp.
 {
   return nI2CState == I2C_READY;
 }
References I2C_READY, and nI2CState.
I2C_Master_Setup()
void I2C_Master_Setup (long nFrequency)
I²C master setup.
I²C master setup
Parameters
nFrequency I2C frequency
Definition at line 35 of file I2C_Master.cpp.
 {
   nI2CState = I2C_READY;
   TWBR = ( CPU_FREQ / nFrequency - 16 ) / 2;    // set I²C speed
 //??  setClock(nFrequency);
   Wire.begin();                                 // start I²C bus as master
 }
References CPU_FREQ, I2C_READY, and nI2CState.
Referenced by setup().
I2C_Master_Steady()
void I2C_Master_Steady ()
I²C master steady call.
I²C master steady call
Definition at line 44 of file I2C_Master.cpp.
 {
   switch ( nI2CState )
   {
   case I2C_READY:
     // wait for a new job
     break;
   case I2C_BUSY:
     if ( Wire.available() )
     {
       int   nReceived = 0;
       char  ch;
       while ( Wire.available() )
       {
         ch = Wire.read();                       // receive byte, typically I2C_DATA_MAX as requested
         if ( nReceived < I2C_DATA_MAX )
           szResponse[nReceived++] = ch;         // store received byte
         // else forget it
       }
       szResponse[nReceived] = 0;                // make sure there is a trailing 0
       nResponseLength = nReceived;
       nResponseTime = micros() - nRequestTime;
       nI2CState = I2C_DONE;                     // received complete, expect user fetches response
     }
     else if ( ( micros() - nRequestTime ) >= nResponseTimeOut )
     {                                           // timeout
       nResponseTime = micros() - nRequestTime;  //?? required
       nI2CState = I2C_TIMEOUT;
     }
     break;
   case I2C_DONE:
     // remain here until response has been delivered
     break;
   case I2C_TIMEOUT:
     // remain here until response has been asked
     break;
   }
   delay(1);
 }
References I2C_BUSY, I2C_DATA_MAX, I2C_DONE, I2C_READY, I2C_TIMEOUT, nI2CState, nRequestTime, nResponseLength, nResponseTime, nResponseTimeOut, and szResponse.
Referenced by loop().
I2C_SendRequest()
int I2C_SendRequest (int nSlaveNo, const char *const pszRequest)
Send request to slave.
Send request to slave. Expects a response.
Parameters
nSlaveNo target slave number for the request
pszRequest request message, may be nullptr
Returns
>=0 on success, -1 if busy, -2 if too long
Definition at line 85 of file I2C_Master.cpp.
 {
   if ( nI2CState != I2C_READY )
     return -1;                                  // fail if not ready
   int  nLength = strlen(pszRequest);            // message length
   if ( nLength > I2C_DATA_MAX )
     return -2;                                  // fail, too long
   nI2CState = I2C_BUSY;                         // busy now
   nSlaveNoLast = nSlaveNo;
   nRequestTime = micros();
   Wire.beginTransmission(nSlaveNo);             // transmit to slave device
   Wire.write(pszRequest, nLength);              // send data
   Wire.endTransmission();                       // ends transmitting
   delay(1);
   Wire.requestFrom(nSlaveNo, I2C_DATA_MAX);     // request from slave
   return nLength;                               // request done
 }
References I2C_BUSY, I2C_DATA_MAX, I2C_READY, nI2CState, nRequestTime, and nSlaveNoLast.
Referenced by Task_100ms().
Variable Documentation
I2C_DATA_MAX
const int I2C_DATA_MAX = 132
max request and response length
Definition at line 27 of file I2C_Master.h.
Referenced by I2C_Master_Steady(), I2C_SendRequest(), and Task_100ms().